#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["src/API/ELibrary-UserService.API.csproj", "src/API/"]
COPY ["src/Domain/ELibrary-UserService.Domain.csproj", "src/Domain/"]
COPY ["src/Infrastructure/ELibrary-UserService.Infrastructure.csproj", "src/Infrastructure/"]
RUN dotnet restore "src/API/ELibrary-UserService.API.csproj"
COPY . .
WORKDIR "/src/src/API"
RUN dotnet build "ELibrary-UserService.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ELibrary-UserService.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ELibrary-UserService.API.dll"]